// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {uuid} from '../models';
import {site} from '../models';
import {settings} from '../models';
import {src} from '../models';

export function AbortUpload(arg1:string):Promise<void>;

export function CheckRequirements():Promise<void>;

export function CheckUserAuth():Promise<{[key: string]: any}>;

export function CreateSite(arg1:string,arg2:string,arg3:string):Promise<uuid.UUID>;

export function DeleteSite(arg1:uuid.UUID):Promise<void>;

export function DeploySite(arg1:uuid.UUID,arg2:number,arg3:string):Promise<any>;

export function EstimateStorageCost(arg1:uuid.UUID,arg2:number,arg3:string):Promise<number>;

export function FetchWallets():Promise<any>;

export function FinishUpload(arg1:string):Promise<string>;

export function GenerateWallet():Promise<any>;

export function GetAllNetworks():Promise<any>;

export function GetBalance():Promise<any>;

export function GetPrivateKey(arg1:string):Promise<any>;

export function GetSetting(arg1:string):Promise<string>;

export function GetSite(arg1:uuid.UUID):Promise<site.Site>;

export function GetTestnetToken():Promise<any>;

export function ImportWallet():Promise<void>;

export function ListSettings():Promise<Array<settings.Settings>>;

export function ListSites(arg1:string):Promise<Array<site.Site>>;

export function Logout():Promise<string>;

export function SetSettings(arg1:Array<src.SettingRequest>):Promise<void>;

export function StartUpload(arg1:uuid.UUID,arg2:string):Promise<string>;

export function SwitchAddress(arg1:string):Promise<any>;

export function SwitchNetwork(arg1:string):Promise<any>;

export function UpdateSite(arg1:uuid.UUID,arg2:string,arg3:string):Promise<void>;

export function UploadChunk(arg1:string,arg2:string):Promise<void>;
