// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortUpload(arg1) {
  return window['go']['src']['App']['AbortUpload'](arg1);
}

export function CheckRequirements() {
  return window['go']['src']['App']['CheckRequirements']();
}

export function CheckUserAuth() {
  return window['go']['src']['App']['CheckUserAuth']();
}

export function CreateSite(arg1, arg2, arg3) {
  return window['go']['src']['App']['CreateSite'](arg1, arg2, arg3);
}

export function DeleteSite(arg1) {
  return window['go']['src']['App']['DeleteSite'](arg1);
}

export function DeploySite(arg1) {
  return window['go']['src']['App']['DeploySite'](arg1);
}

export function FetchWallets() {
  return window['go']['src']['App']['FetchWallets']();
}

export function FinishUpload(arg1) {
  return window['go']['src']['App']['FinishUpload'](arg1);
}

export function GenerateWallet() {
  return window['go']['src']['App']['GenerateWallet']();
}

export function GetSetting(arg1) {
  return window['go']['src']['App']['GetSetting'](arg1);
}

export function GetSite(arg1) {
  return window['go']['src']['App']['GetSite'](arg1);
}

export function ImportWallet() {
  return window['go']['src']['App']['ImportWallet']();
}

export function ListSettings() {
  return window['go']['src']['App']['ListSettings']();
}

export function ListSites() {
  return window['go']['src']['App']['ListSites']();
}

export function SetSettings(arg1) {
  return window['go']['src']['App']['SetSettings'](arg1);
}

export function StartUpload(arg1, arg2) {
  return window['go']['src']['App']['StartUpload'](arg1, arg2);
}

export function UpdateSite(arg1, arg2, arg3) {
  return window['go']['src']['App']['UpdateSite'](arg1, arg2, arg3);
}

export function UploadChunk(arg1, arg2) {
  return window['go']['src']['App']['UploadChunk'](arg1, arg2);
}
