// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {src} from '../models';

export function CheckDownloadStatus():Promise<boolean>;

export function DownloadAllBinaries(arg1:src.NetworkType):Promise<void>;

export function GetProgress():Promise<number>;
