// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDownloadStatus() {
  return window['go']['src']['Downloader']['CheckDownloadStatus']();
}

export function DownloadAllBinaries(arg1) {
  return window['go']['src']['Downloader']['DownloadAllBinaries'](arg1);
}

export function GetProgress() {
  return window['go']['src']['Downloader']['GetProgress']();
}
